<?php

/**
 * Helper function to add specific Foundation JS files.
 *
 * @param $file
 *   The specific JS file to add.
 */
function dd_foundation_add_foundation_js($file = '') {
  $path_to_foundation = libraries_get_path('foundation-sites');

  $scripts = drupal_add_js();

  // Always make sure we add the Foundation JS file.
  if (!isset($scripts[$path_to_foundation . '/js/foundation.core.js'])) {
    drupal_add_js($path_to_foundation . '/js/foundation.core.js', array('group' => JS_LIBRARY));
    drupal_add_js($path_to_foundation . '/js/foundation.util.box.js', array('group' => JS_LIBRARY));
    drupal_add_js($path_to_foundation . '/js/foundation.util.keyboard.js', array('group' => JS_LIBRARY));
    drupal_add_js($path_to_foundation . '/js/foundation.util.mediaQuery.js', array('group' => JS_LIBRARY));
    drupal_add_js($path_to_foundation . '/js/foundation.util.motion.js', array('group' => JS_LIBRARY));
    drupal_add_js($path_to_foundation . '/js/foundation.util.nest.js', array('group' => JS_LIBRARY));
    drupal_add_js($path_to_foundation . '/js/foundation.util.timerAndImageLoader.js', array('group' => JS_LIBRARY));
    drupal_add_js($path_to_foundation . '/js/foundation.util.touch.js', array('group' => JS_LIBRARY));
    drupal_add_js($path_to_foundation . '/js/foundation.util.triggers.js', array('group' => JS_LIBRARY));
  }

  if (!isset($scripts[drupal_get_path('module', 'dd_foundation') . '/js/foundation.js'])) {
    drupal_add_js(drupal_get_path('module', 'dd_foundation') . '/js/foundation.js');
  }

  if (!empty($file) && !isset($scripts[$path_to_foundation . '/js/' . $file])) {
    drupal_add_js($path_to_foundation . '/js/' . $file, array('group' => JS_LIBRARY));
  }
}

/**
 * Implements hook_theme().
 */
function dd_foundation_theme() {
  $return = array();

  $return['dd_foundation_img_interchange'] = array(
    'template' => 'dd-foundation-img-interchange',
    'variables' => array(
      'small' => null,
      'medium' => null,
      'large' => null,
      'alt' => '',
      'title' => '',
    ),
  );

  return $return;
}

/**
 * Implements hook_preprocess().
 */
function dd_foundation_preprocess_dd_foundation_img_interchange(&$variables) {
  dd_foundation_add_foundation_js('foundation.interchange.js');

  // Fallback to small image if medium one is not uploaded.
  if (empty($variables['medium'])) {
    $variables['medium'] = $variables['small'];
  }

  // Fallback to medium image if large one is not uploaded.
  if (empty($variables['large'])) {
    $variables['large'] = $variables['medium'];
  }

  $variables['small'] = image_style_url('dd_small', $variables['small']);
  $variables['medium'] = image_style_url('dd_medium', $variables['medium']);
  $variables['large'] = image_style_url('dd_large', $variables['large']);
}
